### ISSUE TITLE
Something wrong with the 0.1.16 release

### ISSUE THREAD

**Issue by andreasknoepfle** [produtoreativo/react-leaflet-googlemutant#7]
Is it possible that there is something wrong with the new release? 

With the master branch including my PR #4 I now don't get the deprecation warning anymore. 
But the 0.1.16 release installed via `yarn` still issues the warning and when I look into the `node_modules` directory the package has the new 0.1.16 version in the package.json, but still includes the old code from `lib/react-leaflet-googlemutant` from before the PR that issued the warning...

**Comment by andreasknoepfle** [comment]
With: 
```
    "react-leaflet-googlemutant": "git+https://github.com/produtoreativo/react-leaflet-googlemutant.git"
```
in my package.json everything works just fine btw.

**Comment by cmilfont** [comment]
Hi man, i'm sorry for my fault, i don't run update before build.
Try 0.1.18 please!
